name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: ng build --prod --output-path dist

    outputs:
      build_output_path: ${{ steps.build.outputs.build_output_path }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Copy build output to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: build_output
          path: ${{ outputs.build_output_path }}
      - name: Deploy GitHub Pages
        run: gh-pages -d dist/
